/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ownerSol from "./Owner.sol";
export type { ownerSol };
export type { ERC165 } from "./ERC165";
export type { IERC165 } from "./IERC165";
